import type { OpeningDefinition, OpeningLine } from "./types";

function line(
  id: string,
  name: string,
  eco: string,
  moves: string[]
): OpeningLine {
  return { id, name, eco, moves };
}

/** Caro-Kann Defense — ECO B10–B19 repertoire lines. */
export const CARO_KANN_LINES: OpeningLine[] = [
  // ── B10: 1.e4 c6 ─────────────────────────────────────────────
  line("b10-main", "Caro-Kann Defence", "B10", ["e4", "c6"]),

  // Sidelines before 2.d4
  line("b10-hillbilly", "Hillbilly Attack", "B10", ["e4", "c6", "Bc4"]),
  line("b10-hillbilly-d5", "Hillbilly … d5", "B10", ["e4", "c6", "Bc4", "d5"]),
  line("b10-anti", "Anti-Caro-Kann", "B10", ["e4", "c6", "c4"]),
  line("b10-anti-d5", "Anti-Anti-Caro-Kann", "B10", ["e4", "c6", "c4", "d5"]),
  line("b10-anti-d5-exd", "Anti-Anti … exd5", "B10", [
    "e4",
    "c6",
    "c4",
    "d5",
    "cxd5",
    "cxd5",
  ]),
  line("b10-breyer", "Closed (Breyer) Variation", "B11", ["e4", "c6", "d3"]),
  line("b10-breyer-d5", "Breyer … d5", "B11", ["e4", "c6", "d3", "d5"]),
  line("b10-breyer-d5-nc3", "Breyer … Nc3", "B11", [
    "e4",
    "c6",
    "d3",
    "d5",
    "Nd2",
  ]),

  // ── B11: Two Knights & Nc3 systems ───────────────────────────
  line("b11-nc3", "Caro-Kann … Nc3", "B11", ["e4", "c6", "Nc3"]),
  line("b11-two-knights", "Two Knights Variation", "B11", [
    "e4",
    "c6",
    "Nc3",
    "d5",
    "Nf3",
  ]),
  line("b11-two-knights-bg4", "Two Knights … Bg4", "B11", [
    "e4",
    "c6",
    "Nc3",
    "d5",
    "Nf3",
    "Bg4",
  ]),
  line("b11-two-knights-dxe4", "Two Knights … dxe4", "B11", [
    "e4",
    "c6",
    "Nc3",
    "d5",
    "Nf3",
    "dxe4",
    "Nxe4",
    "Nd7",
  ]),
  line("b11-two-knights-nf6", "Two Knights … Nf6", "B11", [
    "e4",
    "c6",
    "Nc3",
    "d5",
    "Nf3",
    "Nf6",
  ]),
  line("b11-two-knights-transposed", "Two Knights (Nf3 first)", "B11", [
    "e4",
    "c6",
    "Nf3",
    "d5",
    "Nc3",
  ]),
  line("b11-goldman", "Goldman (Spielmann) Variation", "B11", [
    "e4",
    "c6",
    "Nc3",
    "d5",
    "Qf3",
  ]),

  // ── B12: 2.d4 d5 — Advance & Fantasy ─────────────────────────
  line("b12-main", "Main Line … d4 d5", "B12", ["e4", "c6", "d4", "d5"]),

  line("b12-advance", "Advance Variation", "B12", ["e4", "c6", "d4", "d5", "e5"]),
  line("b12-advance-bf5", "Advance … Bf5", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "e5",
    "Bf5",
  ]),
  line("b12-advance-bf5-be2", "Advance … Be2", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "e5",
    "Bf5",
    "Be2",
  ]),
  line("b12-advance-bf5-nc3", "Advance … Nc3", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "e5",
    "Bf5",
    "Nc3",
  ]),
  line("b12-advance-bf5-nf3", "Advance … Nf3", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "e5",
    "Bf5",
    "Nf3",
  ]),
  line("b12-advance-c5", "Advance … c5", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "e5",
    "c5",
  ]),

  line("b12-fantasy", "Fantasy Variation", "B12", ["e4", "c6", "d4", "d5", "f3"]),
  line("b12-fantasy-e6", "Fantasy … e6", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "f3",
    "e6",
  ]),
  line("b12-fantasy-g6", "Fantasy … g6", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "f3",
    "g6",
  ]),
  line("b12-fantasy-qb6", "Fantasy … Qb6", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "f3",
    "Qb6",
  ]),
  line("b12-fantasy-dxe4", "Fantasy … dxe4", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "f3",
    "dxe4",
    "fxe4",
    "e5",
  ]),

  // ── B13: Exchange Variation ───────────────────────────────────
  line("b13-exchange", "Exchange Variation", "B13", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
  ]),
  line("b13-exchange-bd3", "Exchange … Bd3", "B13", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "Bd3",
  ]),
  line("b13-exchange-bd3-nc6", "Exchange … Nc6", "B13", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "Bd3",
    "Nc6",
  ]),
  line("b13-exchange-nf3", "Exchange … Nf3", "B13", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "Nf3",
  ]),
  line("b13-exchange-c4", "Exchange … c4", "B13", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "c4",
  ]),

  // ── B14: Panov-Botvinnik Attack ───────────────────────────────
  line("b14-panov", "Panov-Botvinnik Attack", "B14", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "c4",
  ]),
  line("b14-panov-nf6", "Panov … Nf6", "B14", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "c4",
    "Nf6",
  ]),
  line("b14-panov-nf6-nc3", "Panov … Nc3", "B14", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "c4",
    "Nf6",
    "Nc3",
  ]),
  line("b14-panov-e6", "Panov … e6", "B14", [
    "e4",
    "c6",
    "d4",
    "d5",
    "exd5",
    "cxd5",
    "c4",
    "e6",
  ]),

  // ── B15–B16: 3.Nc3 / 3.Nd2 ───────────────────────────────────
  line("b15-nc3", "Main Line … Nc3", "B15", ["e4", "c6", "d4", "d5", "Nc3"]),
  line("b15-nc3-dxe4", "3.Nc3 dxe4", "B15", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
  ]),
  line("b16-nd2", "Main Line … Nd2", "B16", ["e4", "c6", "d4", "d5", "Nd2"]),
  line("b16-nd2-dxe4", "3.Nd2 dxe4", "B16", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
  ]),

  // ── B17: Karpov & 4…Nf6 ──────────────────────────────────────
  line("b17-karpov", "Karpov Variation", "B17", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
    "Nxe4",
    "Nd7",
  ]),
  line("b17-karpov-ng5", "Karpov … Ng5", "B17", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
    "Nxe4",
    "Nd7",
    "Ng5",
  ]),
  line("b17-karpov-nf3", "Karpov … Nf3", "B17", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
    "Nxe4",
    "Nd7",
    "Nf3",
    "Ngf6",
  ]),

  line("b17-nf6-nc3", "4…Nf6 (Nc3)", "B17", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
    "Nxe4",
    "Nf6",
  ]),
  line("b17-nf6-nc3-nxf6", "4…Nf6 … Nxf6+", "B17", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
    "Nxe4",
    "Nf6",
    "Nxf6+",
    "exf6",
  ]),
  line("b17-nf6-nd2", "4…Nf6 (Nd2)", "B17", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
    "Nxe4",
    "Nf6",
  ]),

  // ── B18: Classical Variation ──────────────────────────────────
  line("b18-classical", "Classical Variation", "B18", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
    "Nxe4",
    "Bf5",
  ]),
  line("b18-classical-ng3", "Classical … Ng3", "B18", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
    "Nxe4",
    "Bf5",
    "Ng3",
    "Bg6",
  ]),
  line("b18-classical-nd2", "Classical (Nd2)", "B18", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
    "Nxe4",
    "Bf5",
  ]),
  line("b18-classical-nd2-ng3", "Classical (Nd2) … Ng3", "B18", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nd2",
    "dxe4",
    "Nxe4",
    "Bf5",
    "Ng3",
    "Bg6",
  ]),

  // ── Other main-line branches ────────────────────────────────────
  line("b15-nc3-nd7", "4…Nd7 (Nc3)", "B15", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
    "Nxe4",
    "Nd7",
  ]),
  line("b15-nc3-e5", "4…e5 (Nc3)", "B15", [
    "e4",
    "c6",
    "d4",
    "d5",
    "Nc3",
    "dxe4",
    "Nxe4",
    "e5",
  ]),
  line("b12-g4", "Gurgenidze / 3.g4", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "g4",
  ]),
  line("b12-f4", "Maroczy / 3.f4", "B12", ["e4", "c6", "d4", "d5", "f4"]),
  line("b12-e5-alt", "Tal Variation (3.e5)", "B12", [
    "e4",
    "c6",
    "d4",
    "d5",
    "e5",
    "Bf5",
    "h4",
  ]),
];

export const CARO_KANN: OpeningDefinition = {
  id: "caro-kann",
  name: "Caro-Kann Defense",
  repertoireSide: "black",
  playableAs: "both",
  ecoRange: "B10–B19",
  description:
    "1.e4 c6 — a solid defense where Black supports …d5 and keeps the light-squared bishop free. " +
    "Includes Classical, Advance, Exchange, Panov-Botvinnik, Fantasy, Karpov, and B10 sidelines.",
  entryMoves: "1.e4 c6",
  lines: CARO_KANN_LINES,
};
