import type { OpeningDefinition, OpeningLine } from "./types";

function line(
  id: string,
  name: string,
  eco: string,
  moves: string[]
): OpeningLine {
  return { id, name, eco, moves };
}

/**
 * Ruy Lopez (Spanish Opening) — ECO C60+ repertoire lines.
 * SAN follows chess.js: Bb5 = bishop to b5, O-O = kingside castle.
 */
export const RUY_LOPEZ_LINES: OpeningLine[] = [
  // ── C60: 3.Bb5 ───────────────────────────────────────────────
  line("c60-main", "Ruy Lopez (Spanish Opening)", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
  ]),

  line("c60-nuernberg", "Nuernberg Variation", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "f6",
  ]),
  line("c60-pollock", "Pollock Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Na5",
  ]),
  line("c60-lucena", "Lucena Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Be7",
  ]),
  line("c60-vinogradov", "Vinogradov Variation", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Qe7",
  ]),
  line("c60-brentano", "Brentano Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "g5",
  ]),
  line("c60-fianchetto", "Fianchetto (Smyslov/Barnes) Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "g6",
  ]),

  // ── Secondary defences on move 3 ─────────────────────────────
  line("c60-cozio", "Cozio Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nge7",
  ]),
  line("c60-cozio-paulsen", "Cozio … Paulsen", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nge7",
    "Nc3",
    "g6",
  ]),
  line("c60-bird", "Bird's Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nd4",
  ]),
  line("c60-steinitz", "Steinitz Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "d6",
  ]),
  line("c60-schliemann", "Schliemann Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "f5",
  ]),
  line("c60-cordel", "Classical (Cordel) Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Bc5",
  ]),
  line("c60-berlin", "Berlin Defence", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nf6",
  ]),

  // ── Exchange Variation ─────────────────────────────────────────
  line("c68-exchange", "Exchange Variation", "C68", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Bxc6",
  ]),
  line("c68-exchange-d7", "Exchange … dxc6", "C68", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Bxc6",
    "dxc6",
  ]),

  // ── Open System ────────────────────────────────────────────────
  line("c80-open", "Open System", "C80", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Nxe4",
  ]),
  line("c80-open-berlin", "Open System (via Berlin)", "C80", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nf6",
    "O-O",
    "Nxe4",
  ]),

  // ── Closed System main line ────────────────────────────────────
  line("c84-closed", "Closed System", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
  ]),
  line("c88-closed-main", "Closed Defence", "C88", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
  ]),

  // ── Closed: 9th-move sub-variations ────────────────────────────
  line("c89-pilnik", "Pilnik Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "d3",
  ]),
  line("c89-yates", "Yates Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "d4",
  ]),
  line("c89-chigorin", "Chigorin Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Na5",
  ]),
  line("c89-breyer", "Breyer Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Nb8",
  ]),
  line("c89-zaitsev", "Zaitsev Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Bb7",
  ]),
  line("c89-karpov", "Karpov Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Nd7",
  ]),
  line("c89-kholmov", "Kholmov Variation", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Be6",
  ]),
  line("c89-smyslov-closed", "Smyslov Variation (Closed)", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "h6",
  ]),

  // ── Alternatives to 6.Re1 main line ────────────────────────────
  line("c84-center-attack", "Center Attack", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "d4",
  ]),
  line("c84-modern", "Modern Line (Martinez)", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "d3",
  ]),
  line("c84-morphy", "Morphy Attack", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Nc3",
  ]),
  line("c84-delayed-exchange", "Delayed Exchange Variation", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Bxc6",
  ]),
  line("c84-averbakh", "Averbakh Variation", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "d6",
  ]),
  line("c84-worrall", "Worrall Attack", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Qe2",
  ]),

  // ── Modern Steinitz ────────────────────────────────────────────
  line("c76-modern-steinitz", "Modern Steinitz", "C76", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "d6",
  ]),

  // ── Berlin sub-lines ───────────────────────────────────────────
  line("c67-berlin-d6", "Berlin … d6", "C67", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nf6",
    "O-O",
    "d6",
  ]),
  line("c67-berlin-nxe4", "Berlin … Nxe4", "C67", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nf6",
    "O-O",
    "Nxe4",
  ]),

  // ── Schliemann / Cordel follow-ups ─────────────────────────────
  line("c70-schliemann-nc3", "Schliemann … Nc3", "C70", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "f5",
    "Nc3",
  ]),
  line("c70-schliemann-d3", "Schliemann … d3", "C70", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "f5",
    "d3",
  ]),
  line("c64-cordel-c3", "Cordel … c3", "C64", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Bc5",
    "c3",
  ]),
  line("c64-cordel-o-o", "Cordel … O-O", "C64", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Bc5",
    "O-O",
  ]),

  // ── Steinitz follow-up ─────────────────────────────────────────
  line("c62-steinitz-d4", "Steinitz … d4", "C62", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "d6",
    "d4",
  ]),

  // ── Bird's follow-up ───────────────────────────────────────────
  line("c61-bird-main", "Bird's … Nxd4", "C61", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nd4",
    "Nxd4",
    "exd4",
  ]),

  // ── Yates Bogoljubow branch ────────────────────────────────────
  line("c89-yates-bogo", "Yates … Bogoljubow (Bg4)", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "d4",
    "Bg4",
  ]),

  // ── Extended closed / Chigorin / Breyer / Kholmov ──────────────
  line("c89-chigorin-qc7", "Chigorin … Qc7", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Na5",
    "Bc2",
    "c5",
    "d4",
    "Qc7",
  ]),
  line("c89-breyer-ng3", "Breyer … Nf1", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Nb8",
    "d4",
    "Nbd7",
    "Nbd2",
    "Bb7",
    "Nf1",
  ]),
  line("c89-kholmov-d4", "Kholmov … d4", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "h3",
    "Be6",
    "d4",
  ]),
  line("c89-pilnik-nbd2", "Pilnik … Nbd2", "C89", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Re1",
    "b5",
    "Bb3",
    "d6",
    "c3",
    "O-O",
    "d3",
    "Nb8",
    "Nbd2",
  ]),

  // ── Center Attack / Modern / Morphy continuations ──────────────
  line("c84-center-exd4", "Center Attack … exd4", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "d4",
    "exd4",
    "Nxd4",
  ]),
  line("c84-center-e5", "Center Attack … e5", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "d4",
    "exd4",
    "Nxd4",
    "Nxd4",
    "Qxd4",
    "O-O",
    "e5",
  ]),
  line("c84-modern-d6", "Modern Line … d6", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "d3",
    "d6",
    "c3",
  ]),
  line("c84-modern-b5", "Modern Line … b5", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "d3",
    "b5",
    "Bb3",
  ]),
  line("c84-morphy-b5", "Morphy Attack … b5", "C84", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Be7",
    "Nc3",
    "b5",
    "Bb3",
  ]),

  // ── Fianchetto / Steinitz / Lucena / Pollock ───────────────────
  line("c60-fianchetto-c3", "Fianchetto … c3", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "g6",
    "c3",
  ]),
  line("c60-fianchetto-d4", "Fianchetto … d4 Bg5", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "g6",
    "d4",
    "exd4",
    "Bg5",
  ]),
  line("c62-steinitz-c3", "Steinitz … c3", "C62", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "d6",
    "c3",
  ]),
  line("c62-steinitz-o-o", "Steinitz … O-O", "C62", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "d6",
    "O-O",
  ]),
  line("c60-lucena-d4", "Lucena … d4", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Be7",
    "d4",
  ]),
  line("c60-pollock-ba4", "Pollock … Ba4", "C60", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Na5",
    "Ba4",
  ]),

  // ── Open System / Exchange follow-ups ──────────────────────────
  line("c80-open-re1", "Open System … Re1", "C80", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Ba4",
    "Nf6",
    "O-O",
    "Nxe4",
    "Re1",
  ]),
  line("c68-exchange-d5", "Exchange … d5", "C68", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "a6",
    "Bxc6",
    "dxc6",
    "d4",
  ]),
  line("c64-cordel-nf6", "Cordel … Nf6", "C64", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Bc5",
    "O-O",
    "Nf6",
  ]),
  line("c61-bird-full", "Bird's Defence (main line)", "C61", [
    "e4",
    "e5",
    "Nf3",
    "Nc6",
    "Bb5",
    "Nd4",
    "Nxd4",
    "exd4",
    "O-O",
    "Bc5",
    "d3",
    "c6",
    "Ba4",
    "Ne7",
  ]),
];

export const RUY_LOPEZ: OpeningDefinition = {
  id: "ruy-lopez",
  name: "Ruy Lopez (Spanish Opening)",
  repertoireSide: "white",
  playableAs: "both",
  ecoRange: "C60–C99",
  description:
    "1.e4 e5 2.Nf3 Nc6 3.Bb5 — White pressures the e5 pawn via the knight on c6. " +
    "Includes Closed, Open, Exchange, Berlin, and secondary defences.",
  entryMoves: "1.e4 e5 2.Nf3 Nc6 3.Bb5",
  lines: RUY_LOPEZ_LINES,
};
