import type { OpeningDefinition, OpeningLine } from "./types";

function line(
  id: string,
  name: string,
  eco: string,
  moves: string[]
): OpeningLine {
  return { id, name, eco, moves };
}

/**
 * Sicilian Defense — ECO B20+ repertoire lines.
 * SAN follows chess.js: Bb5 = bishop to b5, O-O = kingside castle.
 */
export const SICILIAN_LINES: OpeningLine[] = [
  // ── B20: 1.e4 c5 ─────────────────────────────────────────────
  line("b20-main", "Sicilian Defence", "B20", ["e4", "c5"]),

  // ── Anti-Sicilians & sidelines for White ─────────────────────
  line("b22-alapin", "Alapin Variation", "B22", ["e4", "c5", "c3"]),
  line("b22-alapin-nf6", "Alapin … Nf6", "B22", ["e4", "c5", "c3", "Nf6"]),
  line("b22-alapin-d5", "Alapin … d5", "B22", ["e4", "c5", "c3", "d5"]),
  line("b22-alapin-e6", "Alapin … e6", "B22", ["e4", "c5", "c3", "e6"]),
  line("b22-alapin-d6", "Alapin … d6", "B22", ["e4", "c5", "c3", "d6"]),
  line("b22-alapin-g6", "Alapin … g6", "B22", ["e4", "c5", "c3", "g6"]),

  line("b23-closed", "Closed Sicilian", "B23", ["e4", "c5", "Nc3"]),
  line("b23-closed-nc6", "Closed Sicilian … Nc6", "B23", [
    "e4",
    "c5",
    "Nc3",
    "Nc6",
  ]),
  line("b23-closed-d6", "Closed Sicilian … d6", "B23", ["e4", "c5", "Nc3", "d6"]),
  line("b23-closed-e6", "Closed Sicilian … e6", "B23", ["e4", "c5", "Nc3", "e6"]),
  line("b23-closed-a6", "Closed Sicilian … a6", "B23", ["e4", "c5", "Nc3", "a6"]),
  line("b23-closed-g6", "Closed Sicilian … g6", "B23", ["e4", "c5", "Nc3", "g6"]),

  line("b24-g3", "Sicilian with 2.g3", "B24", ["e4", "c5", "g3"]),
  line("b25-okelly", "O'Kelly Variation", "B25", ["e4", "c5", "Nf3", "a6"]),
  line("b27-nimzowitsch", "Nimzowitsch Variation", "B27", [
    "e4",
    "c5",
    "Nf3",
    "Nf6",
  ]),
  line("b29-grand-prix", "Grand Prix Attack", "B29", [
    "e4",
    "c5",
    "Nc3",
    "Nc6",
    "f4",
  ]),
  line("b41-morra", "Smith-Morra Gambit", "B41", [
    "e4",
    "c5",
    "d4",
    "cxd4",
    "c3",
  ]),

  // ── Rossolimo / Moscow ─────────────────────────────────────────
  line("b30-rossolimo", "Rossolimo Variation", "B30", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "Bb5",
  ]),
  line("b32-moscow", "Moscow Variation", "B32", ["e4", "c5", "Nf3", "d6", "Bb5+"]),

  // ── Open Sicilian: 2…d6 ───────────────────────────────────────
  line("b50-open", "Open Sicilian", "B50", ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4"]),
  line("b50-open-nf6", "Open Sicilian … Nf6", "B50", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
  ]),
  line("b50-open-nc3", "Open Sicilian … Nc3", "B50", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
  ]),

  // ── Najdorf ────────────────────────────────────────────────────
  line("b90-najdorf", "Sicilian Najdorf", "B90", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
  ]),
  line("b90-najdorf-be3", "Najdorf … Be3", "B90", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "Be3",
  ]),
  line("b92-najdorf-be2", "Najdorf … Be2", "B92", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "Be2",
  ]),
  line("b96-najdorf-bg5", "Najdorf … Bg5", "B96", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "Bg5",
  ]),
  line("b90-najdorf-h3", "Adams Attack", "B51", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "h3",
  ]),
  line("b89-najdorf-bc4", "Najdorf … Bc4", "B89", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "Bc4",
  ]),
  line("b93-najdorf-f4", "Najdorf … f4", "B93", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "f4",
  ]),
  line("b90-najdorf-f3", "Najdorf … f3", "B90", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "f3",
  ]),
  line("b91-najdorf-g3", "Najdorf … g3", "B91", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "a6",
    "g3",
  ]),

  // ── Scheveningen ───────────────────────────────────────────────
  line("b84-scheveningen", "Scheveningen Variation", "B84", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
  ]),
  line("b84-scheveningen-g4", "Scheveningen … g4", "B84", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
    "g4",
  ]),
  line("b84-scheveningen-be2", "Scheveningen … Be2", "B84", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
    "Be2",
  ]),
  line("b84-scheveningen-be3", "Scheveningen … Be3", "B84", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
    "Be3",
  ]),
  line("b84-scheveningen-f4", "Scheveningen … f4", "B84", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
    "f4",
  ]),
  line("b84-scheveningen-g3", "Scheveningen … g3", "B84", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
    "g3",
  ]),
  line("b88-sozin", "Sozin Variation", "B88", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e6",
    "Bc4",
  ]),

  // ── Classical Sicilian ─────────────────────────────────────────
  line("b54-classical", "Classical Sicilian", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
  ]),
  line("b58-classical-bg5", "Richter-Rauzer Variation", "B58", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "Bg5",
  ]),
  line("b58-classical-main", "Classical … Bg5 main line", "B58", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "Bg5",
    "e6",
    "Qd2",
    "a6",
    "O-O-O",
    "Bd7",
    "f4",
    "b5",
    "Bxf6",
    "gxf6",
  ]),
  line("b54-classical-bc4", "Classical … Bc4", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "Bc4",
  ]),
  line("b54-classical-be2", "Classical … Be2", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "Be2",
  ]),
  line("b54-classical-f3", "Classical … f3", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "f3",
  ]),
  line("b54-classical-g3", "Classical … g3", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "g3",
  ]),
  line("b54-classical-be3", "Classical … Be3", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "Be3",
  ]),
  line("b54-classical-f4", "Classical … f4", "B54", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "f4",
  ]),

  // ── Dragon ─────────────────────────────────────────────────────
  line("b70-dragon", "Sicilian Dragon", "B70", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "g6",
  ]),
  line("b75-yugoslav", "Yugoslav Attack", "B75", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "g6",
    "Be3",
    "Bg7",
    "f3",
    "O-O",
    "Qd2",
    "Nc6",
    "Bc4",
  ]),
  line("b72-classical-dragon", "Classical Dragon", "B72", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "g6",
    "Be2",
  ]),
  line("b76-levenfish", "Levenfish Attack", "B76", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "g6",
    "f4",
  ]),
  line("b76-levenfish-main", "Levenfish … main line", "B76", [
    "e4",
    "c5",
    "Nf3",
    "d6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "g6",
    "f4",
    "Nc6",
    "Nxc6",
    "bxc6",
    "e5",
    "Nd7",
    "exd6",
    "exd6",
    "Be3",
    "Be7",
    "Qd2",
    "O-O",
    "O-O-O",
    "Nf6",
  ]),

  // ── Accelerated / Hyper-Accelerated Dragon ─────────────────────
  line("b34-accel-dragon", "Accelerated Dragon", "B34", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "g6",
  ]),
  line("b34-accel-c4", "Accelerated Dragon … c4", "B34", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "g6",
    "c4",
  ]),
  line("b34-accel-nc3", "Accelerated Dragon … Nc3", "B34", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "g6",
    "Nc3",
  ]),
  line("b43-hyper-dragon", "Hyper-Accelerated Dragon", "B43", [
    "e4",
    "c5",
    "Nf3",
    "g6",
  ]),

  // ── Sveshnikov / Lowenthal / Kalashnikov ───────────────────────
  line("b33-sveshnikov", "Sveshnikov Variation", "B33", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "e5",
  ]),
  line("b60-lowenthal", "Lowenthal Variation", "B60", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "e5",
  ]),
  line("b32-kalashnikov", "Kalashnikov Variation", "B32", [
    "e4",
    "c5",
    "Nf3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "e5",
    "Nb5",
    "d6",
  ]),

  // ── Kan / Taimanov / Four Knights / Pin ────────────────────────
  line("b46-kan", "Kan (Paulsen) Sicilian", "B46", [
    "e4",
    "c5",
    "Nf3",
    "e6",
    "d4",
    "cxd4",
    "Nxd4",
    "a6",
  ]),
  line("b47-taimanov", "Taimanov Variation", "B47", [
    "e4",
    "c5",
    "Nf3",
    "e6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nc6",
  ]),
  line("b48-four-knights", "Four Knights Sicilian", "B48", [
    "e4",
    "c5",
    "Nf3",
    "e6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
  ]),
  line("b48-four-knights-main", "Four Knights … main line", "B48", [
    "e4",
    "c5",
    "Nf3",
    "e6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Nc6",
    "Ndb5",
    "d6",
    "Bf4",
    "e5",
    "Bg5",
    "a6",
    "Na3",
    "b5",
    "Nd5",
    "Be7",
    "Bxf6",
    "Bxf6",
    "c3",
    "O-O",
  ]),
  line("b44-pin", "Pin (Counter-Attack) Variation", "B44", [
    "e4",
    "c5",
    "Nf3",
    "e6",
    "d4",
    "cxd4",
    "Nxd4",
    "Nf6",
    "Nc3",
    "Bb4",
  ]),

  // ── 2…e6 Open Sicilian (without d6 first) ──────────────────────
  line("b40-e6-open", "Open Sicilian … 2…e6", "B40", [
    "e4",
    "c5",
    "Nf3",
    "e6",
    "d4",
    "cxd4",
    "Nxd4",
  ]),

  // ── 2…Nc6 before d4 ────────────────────────────────────────────
  line("b30-nc6", "Sicilian … 2…Nc6", "B30", ["e4", "c5", "Nf3", "Nc6"]),
];

export const SICILIAN: OpeningDefinition = {
  id: "sicilian",
  name: "Sicilian Defence",
  repertoireSide: "black",
  playableAs: "both",
  ecoRange: "B20–B99",
  description:
    "1.e4 c5 — Black fights for the centre with queenside counterplay. " +
    "Includes Najdorf, Dragon, Classical, Scheveningen, Anti-Sicilians, and more.",
  entryMoves: "1.e4 c5",
  lines: SICILIAN_LINES,
};
